# Generated by Django 2.2.15 on 2020-08-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='read',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
